# The top-level targets paths.
fulcio_v1.crt.pem:
  sigstore:
    uri: https://fulcio.sigstore.dev
    usage: Fulcio
    status: Active
fulcio_intermediate_v1.crt.pem:
  sigstore:
    uri: https://fulcio.sigstore.dev
    usage: Fulcio
    status: Active
fulcio.crt.pem:
  sigstore:
    uri: https://fulcio.sigstore.dev
    usage: Fulcio
    status: Expired
ctfe.pub:
  sigstore:
    uri: https://ctfe.sigstore.dev
    usage: CTFE
    status: Active
ctfe_2022.pub:
  sigstore:
    uri: https://ctfe.sigstore.dev
    usage: CTFE
    status: Active
rekor.pub:
  sigstore:
    uri: https://rekor.sigstore.dev
    usage: Rekor
    status: Active
artifact.pub:
  sigstore:
    usage: Unknown
    status: Active
