name: Snapshot and Timestamp

# Execute this as a biweekly cron job and on changes to repository/ 
# when new published metadata is submitted.
on:
  # Enable cron when repository published with these keys. 
  # schedule:
  #   cron: '0 0 */14 * *' # every 14 days
  push:
    branches: [ main ]
    paths:
      - 'repository/**'

jobs:  
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: setup
      - run: |
          echo "REPO=$(pwd)/repository/" >> $GITHUB_ENV
          echo "SNAPSHOT_KEY=gcpkms://projects/project-rekor/locations/global/keyRings/sigstore-root/cryptoKeys/snapshot" >> $GITHUB_ENV
          echo "TIMESTAMP_KEY=gcpkms://projects/project-rekor/locations/global/keyRings/sigstore-root/cryptoKeys/snapshot" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - uses: 'google-github-actions/setup-gcloud@v0.2.1'
        with:
          project_id: asra-ali
      # Setup OIDC->SA auth
      - uses: 'google-github-actions/auth@v0.3.0'
        id: auth
        with:
          workload_identity_provider: 'projects/237800849078/locations/global/workloadIdentityPools/root-signing-pool/providers/sigstore-root'
          service_account: 'sigstore-root-signing@project-rekor.iam.gserviceaccount.com'
          create_credentials_file: true
      - name: Login
        run: |
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"

      # Snapshot and timestamp    
      - name: build
        run: go build -o tuf ./cmd/tuf/
      - name: snapshot
        run: |
          ./tuf snapshot -repository $REPO
          ./tuf sign -repository $REPO -roles snapshot -key ${SNAPSHOT_KEY}
          ./tuf timestamp -repository $REPO
          ./tuf sign -repository $REPO -roles timestamp -key ${TIMESTAMP_KEY}
      - name: publish
        run: ./tuf publish -repository $REPO