name: CI Validate

on:
  push:
    branches: [ main ]
    paths:
      - 'ceremony/**'
      - 'repository/**'
  pull_request:
    branches: [ main ]

jobs:  
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo "REPO=$(pwd)/repository" >> $GITHUB_ENV
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - name: install deps
        run: | 
          sudo apt-get install libpcsclite-dev
          curl -fsO https://developers.yubico.com/PIV/Introduction/piv-attestation-ca.pem
      - name: build
        run: go build -o verify ./cmd/verify/
      - name: build
        run: go build -o tuf -tags=pivkey ./cmd/tuf
      - name: verify
        run: |
          ./verify repository --repository $REPO --root $REPO/repository/1.root.json

